SET FOREIGN_KEY_CHECKS = 0;

DROP DATABASE orz;
# DROP TABLE IF EXISTS `options`;
# DROP TABLE IF EXISTS `operation_record`;
# DROP TABLE IF EXISTS `users`;
# DROP TABLE IF EXISTS `users_profile`;
# DROP TABLE IF EXISTS `department`;
# DROP TABLE IF EXISTS `position`;

SET FOREIGN_KEY_CHECKS = 1;
